In [1]:
import pandas as pd
df = pd.read_csv("TravelInsurancePrediction.csv")

In [2]:
df = df.loc[:,["Age","Employment Type","GraduateOrNot","AnnualIncome","FamilyMembers","ChronicDiseases","FrequentFlyer","EverTravelledAbroad","TravelInsurance"]]


In [3]:
df = df.dropna()

In [4]:
X = df.loc[:,["Age","Employment Type","GraduateOrNot","AnnualIncome","FamilyMembers","ChronicDiseases","FrequentFlyer","EverTravelledAbroad"]]
Y = df.loc[:,["TravelInsurance"]]

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y)

In [6]:
from sklearn import tree
model = tree.DecisionTreeClassifier()
model.fit(X_train, Y_train)    #train the model

DecisionTreeClassifier()

In [7]:
pred = model.predict(X_test)   #run model with test set

In [8]:
len(Y_test)

497

In [9]:
Y_test.sum()

TravelInsurance    173
dtype: int64

In [10]:
from sklearn.metrics import confusion_matrix
import numpy as np
from sklearn.metrics import f1_score, precision_score, recall_score, accuracy_score
cm = confusion_matrix(Y_test, pred)
#cm2 = np.array([cm[1], cm[0]])
print("model: DecisionTreeClassifier")
print(cm)
f1 = f1_score(Y_test, pred)
prec = precision_score(Y_test, pred)
rec = recall_score(Y_test, pred)
acc = accuracy_score(Y_test, pred)
print("Accuracy is:", acc)
print("F1 is:", f1)
print("Precision is:", prec)
print("Recall is:", rec)


model: DecisionTreeClassifier
[[278  46]
 [ 66 107]]
Accuracy is: 0.7746478873239436
F1 is: 0.656441717791411
Precision is: 0.6993464052287581
Recall is: 0.6184971098265896


In [11]:
from sklearn import ensemble
model = ensemble.RandomForestClassifier()
#model = ensemble.GradientBoostingClassifier()
model.fit(X_train, Y_train) 
pred = model.predict(X_test)
cm = confusion_matrix(Y_test, pred)


print("model: RandomForestClassifier")
print(cm)
f1 = f1_score(Y_test, pred)
prec = precision_score(Y_test, pred)
rec = recall_score(Y_test, pred)
acc = accuracy_score(Y_test, pred)
print("Accuracy is:", acc)
print("F1 is:", f1)
print("Precision is:", prec)
print("Recall is:", rec)

C:\Users\Shi Jia Cheng\AppData\Local\Temp\ipykernel_12392\3880957393.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model.fit(X_train, Y_train)


model: RandomForestClassifier
[[290  34]
 [ 65 108]]
Accuracy is: 0.8008048289738431
F1 is: 0.6857142857142857
Precision is: 0.7605633802816901
Recall is: 0.6242774566473989


In [12]:
model = ensemble.GradientBoostingClassifier()
model.fit(X_train, Y_train) 
pred = model.predict(X_test)
cm = confusion_matrix(Y_test, pred)
print("model: GradientBoostingClassifier")
print(cm)
f1 = f1_score(Y_test, pred)
prec = precision_score(Y_test, pred)
rec = recall_score(Y_test, pred)
acc = accuracy_score(Y_test, pred)
print("Accuracy is:", acc)
print("F1 is:", f1)
print("Precision is:", prec)
print("Recall is:", rec)

model: GradientBoostingClassifier
[[309  15]
 [ 76  97]]
Accuracy is: 0.8169014084507042
F1 is: 0.6807017543859649
Precision is: 0.8660714285714286
Recall is: 0.5606936416184971


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [13]:
from sklearn import linear_model
model = linear_model.LogisticRegression()   #regression
model.fit(X_train, Y_train) 
pred = model.predict(X_test)
cm = confusion_matrix(Y_test, pred)
print("model: LogisticRegression")
print(cm)
f1 = f1_score(Y_test, pred)
prec = precision_score(Y_test, pred)
rec = recall_score(Y_test, pred)
acc = accuracy_score(Y_test, pred)
print("Accuracy is:", acc)
print("F1 is:", f1)
print("Precision is:", prec)
print("Recall is:", rec)

model: LogisticRegression
[[324   0]
 [173   0]]
Accuracy is: 0.6519114688128773
F1 is: 0.0
Precision is: 0.0
Recall is: 0.0


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
